name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  checks:
    if: github.event.pull_request.draft == false
    runs-on: self-hosted
    container:
      image: python:3.12-slim
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install
        run: pip install -e ".[dev]"

      - name: Lint
        run: ruff check .

      - name: Type check
        run: mypy

      - name: Unit tests
        run: pytest tests
